<?php

return [
    'json-validator' => [
        'name' => 'JSON Validator',
        'description' => 'Paste JSON to validate, format, and catch errors instantly.',
        'icon' => 'code-bracket',
        'processing' => 'client',
        'category' => 'developer',
        'meta_title' => 'Free JSON Validator & Formatter Online | GadgetDrop',
        'meta_description' => 'Validate and pretty-print JSON instantly in your browser. No upload, no server. 100% private.',
        'related_tags' => ['programming', 'developer-tools'],
    ],
    'js-css-minifier' => [
        'name' => 'JS & CSS Minifier',
        'description' => 'Shrink your JavaScript and CSS files in seconds.',
        'icon' => 'scissors',
        'processing' => 'client',
        'category' => 'developer',
        'meta_title' => 'Free JS & CSS Minifier Online | GadgetDrop',
        'meta_description' => 'Minify JavaScript and CSS instantly in your browser. See exact file size savings.',
        'related_tags' => ['programming', 'web-development', 'performance'],
    ],
    'image-editor' => [
        'name' => 'Image Editor',
        'description' => 'Crop, resize, rotate, and adjust colors in one browser-based editor.',
        'icon' => 'photo',
        'processing' => 'client',
        'category' => 'image',
        'meta_title' => 'Free Online Image Editor: Crop, Resize, Adjust Colors | GadgetDrop',
        'meta_description' => 'Crop, resize, rotate, and adjust colors (exposure, contrast, saturation, temperature, and more) in one free editor. Undo any time, export to JPG, PNG, or WebP. 100% private, nothing is uploaded.',
        'related_tags' => ['photography', 'design', 'tech-accessories'],
    ],
    'image-converter' => [
        'name' => 'Image Converter',
        'description' => 'Convert and resize images to JPG, PNG, or WebP in your browser.',
        'icon' => 'photo',
        'processing' => 'client',
        'category' => 'image',
        'meta_title' => 'Free Image Converter Online | GadgetDrop',
        'meta_description' => 'Convert images to JPG, PNG, or WebP and resize them instantly in your browser. No upload, 100% private.',
        'related_tags' => ['photography', 'design', 'tech-accessories'],
    ],
    'background-remover' => [
        'name' => 'Background Remover',
        'description' => 'Remove white or solid backgrounds from product images instantly.',
        'icon' => 'sparkles',
        'processing' => 'client',
        'category' => 'image',
        'meta_title' => 'Free Background Remover Online | GadgetDrop',
        'meta_description' => 'Remove white or solid backgrounds from product images instantly in your browser. No upload, no AI API. 100% private and free.',
        'related_tags' => ['photography', 'design', 'tech-accessories'],
    ],
    'password-generator' => [
        'name' => 'Password Generator',
        'description' => 'Generate secure, random passwords with custom length and character sets.',
        'icon' => 'key',
        'processing' => 'client',
        'category' => 'developer',
        'meta_title' => 'Free Password Generator Online | GadgetDrop',
        'meta_description' => 'Generate strong, random passwords instantly in your browser. Choose length, symbols, and more. 100% private. Nothing sent to any server.',
        'related_tags' => ['security', 'developer-tools', 'programming'],
    ],
    'base64-encoder' => [
        'name' => 'Base64 Encoder / Decoder',
        'description' => 'Encode or decode Base64 text and files instantly in your browser.',
        'icon' => 'arrows-right-left',
        'processing' => 'client',
        'category' => 'developer',
        'meta_title' => 'Free Base64 Encoder & Decoder Online | GadgetDrop',
        'meta_description' => 'Encode text or files to Base64 and decode Base64 strings instantly in your browser. No server, no upload. 100% private.',
        'related_tags' => ['programming', 'developer-tools', 'web-development'],
    ],
    'color-palette' => [
        'name' => 'Color Palette Extractor',
        'description' => 'Upload any image and extract its dominant colors as HEX, RGB, or HSL.',
        'icon' => 'swatch',
        'processing' => 'client',
        'category' => 'image',
        'meta_title' => 'Free Color Palette Extractor Online | GadgetDrop',
        'meta_description' => 'Extract dominant colors from any image instantly in your browser. Get HEX, RGB, and HSL codes with one click. No upload required.',
        'related_tags' => ['design', 'photography', 'tech-accessories'],
    ],
    'docx-to-pdf' => [
        'name' => 'DOCX to PDF Converter',
        'description' => 'Turn a Word document into a real PDF with selectable text, right on your device.',
        'icon' => 'document',
        'processing' => 'client',
        'category' => 'document',
        'meta_title' => 'Free DOCX to PDF Converter (No Upload) | GadgetDrop',
        'meta_description' => 'Convert Word .docx files to PDF instantly in your browser. Real selectable text, not a screenshot. Pick page size, margins, and font. Nothing is uploaded, 100% private and free.',
        'related_tags' => ['productivity', 'software', 'developer-tools'],
    ],
    'meta-tag-previewer' => [
        'name' => 'Meta Tag Previewer',
        'description' => 'Preview how your page looks in Google search results and social media cards.',
        'icon' => 'magnifying-glass',
        'processing' => 'client',
        'category' => 'developer',
        'meta_title' => 'Free Meta Tag Previewer Online | GadgetDrop',
        'meta_description' => 'Preview your page title, description, and open graph tags as they appear in Google and on Twitter/Facebook. Instant, no server.',
        'related_tags' => ['seo', 'web-development', 'programming'],
    ],
];
