<?php

return [
    'json-validator' => [
        'name'             => 'JSON Validator',
        'description'      => 'Paste JSON to validate, format, and catch errors instantly.',
        'icon'             => 'code-bracket',
        'processing'       => 'client',
        'category'         => 'developer',
        'meta_title'       => 'Free JSON Validator & Formatter Online — GadgetDrop',
        'meta_description' => 'Validate and pretty-print JSON instantly in your browser. No upload, no server — 100% private.',
        'related_tags'     => ['programming', 'developer-tools'],
    ],
    'js-css-minifier' => [
        'name'             => 'JS & CSS Minifier',
        'description'      => 'Shrink your JavaScript and CSS files in seconds.',
        'icon'             => 'scissors',
        'processing'       => 'client',
        'category'         => 'developer',
        'meta_title'       => 'Free JS & CSS Minifier Online — GadgetDrop',
        'meta_description' => 'Minify JavaScript and CSS instantly in your browser. See exact file size savings.',
        'related_tags'     => ['programming', 'web-development', 'performance'],
    ],
    'image-converter' => [
        'name'             => 'Image Converter',
        'description'      => 'Convert and resize images to JPG, PNG, or WebP in your browser.',
        'icon'             => 'photo',
        'processing'       => 'client',
        'category'         => 'image',
        'meta_title'       => 'Free Image Converter Online — GadgetDrop',
        'meta_description' => 'Convert images to JPG, PNG, or WebP and resize them instantly in your browser. No upload, 100% private.',
        'related_tags'     => ['photography', 'design', 'tech-accessories'],
    ],
    'image-cropper' => [
        'name'             => 'Image Cropper',
        'description'      => 'Crop, rotate, and flip images with aspect ratio presets and circle crop.',
        'icon'             => 'crop',
        'processing'       => 'client',
        'category'         => 'image',
        'meta_title'       => 'Free Image Cropper Online — GadgetDrop',
        'meta_description' => 'Crop images with free or preset aspect ratios (1:1, 16:9, 4:3), rotate, flip, and circle crop. Runs entirely in your browser.',
        'related_tags'     => ['photography', 'design', 'tech-accessories'],
    ],
    'background-remover' => [
        'name'             => 'Background Remover',
        'description'      => 'Remove white or solid backgrounds from product images instantly.',
        'icon'             => 'sparkles',
        'processing'       => 'client',
        'category'         => 'image',
        'meta_title'       => 'Free Background Remover Online — GadgetDrop',
        'meta_description' => 'Remove white or solid backgrounds from product images instantly in your browser. No upload, no AI API — 100% private and free.',
        'related_tags'     => ['photography', 'design', 'tech-accessories'],
    ],
];
